name: CI
run-name: Run CI 🚀

on:
  push:
    branches:
      - master
  pull_request:

  workflow_dispatch:

concurrency:
  group: ci-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up & Cache Node.js
        uses: ./.github/actions/setup-and-cache

  lint-and-format:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Load Cache
        uses: ./.github/actions/setup-and-cache
        with:
          node-version: "18"

      - name: Lint code
        run: yarn run lint:check

      - name: Check code formatting
        run: yarn run format:check

  test:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Load Cache
        uses: ./.github/actions/setup-and-cache
        with:
          node-version: "18"

      - name: Run tests
        run: yarn run test --coverage

      - name: "Report Coverage"
        if: always() # Also generate the report if tests are failing
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          name: "Frontend Coverage Report"
          json-summary-path: "./coverage/coverage-summary.json"
          json-final-path: "./coverage/coverage-final.json"

  post-comment:
    if: ${{ github.event_name == 'pull_request' }}
    needs: test
    runs-on: ubuntu-latest

    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Load Cache
        uses: ./.github/actions/setup-and-cache
        with:
          node-version: "18"

      - name: Post workflow status as comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            The workflow run has completed with status: **${{ job.status }}**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
