name: CI
run-name: Run CI 🚀

on:
  push:
    branches:
      - master
  pull_request:

  workflow_dispatch:

jobs:
  post-comment:
    if: ${{ github.event.pull_request.number }}
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Post workflow status as comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            The workflow run has completed with status: **${{ job.status }}**

            github.event.pull_request.author
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
